### ISSUE TITLE
Signup Route not Signing and returning JWT

### ISSUE THREAD

**Issue by bilal42011** [bilal42011/Fyp-Backend#1]
### **Have to set up signup for signing up the JWT and returning it with payload**

**_We want to redirect the user to Dashboard once registration is successful that's possible through the returned token_**

**Thankyou**

**Comment by msafwankarim** [comment]
Implemented 
Commit ID: [0c163f354a5b6e8cc140ea775b7885d46e639498](https://github.com/bilal42011/Customized-Ecommerce-Backend/commit/0c163f354a5b6e8cc140ea775b7885d46e639498)
